Allow extending the model inputs
joeynmt/joeynmt pull request #124
Opened 2020-12-16 14:05 UTC by AmitMY

Large change, happy to discuss this :)

Currently, many of the dataset parameters are hardcoded and explicitly stated when passed to functions.
This, in my opinion, and experience hurts the ability to use `joeynmt` as a library, and extend to use different inputs, or multiple inputs, like images, audio, etc...

This PR does not remove the `src` and `trg` sequences from being text sequences but allows for extending and adding more inputs. 
For example, for every word in `src` I have some features, like its `POS` tag which I'd like to use. Currently, I can't. With this PR, I'll have to change the data loader and just extend the `Batch` class. Not many changes and I can use more inputs.

2020-12-24 14:02 UTC, juliakreutzer requested changes
:100: Thanks a lot, this is a very good idea. Please see my comments for suggested changes.

2020-12-24 15:04 UTC, AmitMY commented on joeynmt/model.py
> +    def _encode_decode(self, trg_input: Tensor, **kwargs) \
Makes sense. I now made the `src` variables explicit

2020-12-24 15:06 UTC, AmitMY commented on joeynmt/training.py
> +    def __init__(self, model: Model, config: dict, batch_class) -> None:
I added a default value (`Batch`), but I, unfortunately, don't know how to type it as "any class that extends `Batch`" - as its a class and not an instance of the class.

2020-12-24 15:09 UTC, AmitMY commented
Thanks @juliakreutzer 
I have addressed your comments, please let me know if there's anything else I should do or justify
Happy holidays.

2021-01-10 23:00 UTC, juliakreutzer commented
Looks good, thanks so much for the changes! Now only the pylint errors left, I'm okay with the unused-argument error skipping for kwargs.

2021-01-10 23:04 UTC, juliakreutzer commented on joeynmt/training.py
> +    def __init__(self, model: Model, config: dict, batch_class) -> None:
That should be fine since it should not be an instance (an instance would be created with `Batch(...)`).
Have you tried running the code?

2021-01-11 06:56 UTC, AmitMY commented on joeynmt/training.py
> +    def __init__(self, model: Model, config: dict, batch_class) -> None:
yes, the code runs, I'm using it locally to train stuff :)

2021-01-11 07:03 UTC, AmitMY commented
Great, I changed to `_kwargs` which makes the linter be ok with them being unused

2021-01-15 23:59 UTC, juliakreutzer approved these changes
Awesome, thanks so much!

2021-01-15 23:59 UTC, merged

2021-01-16 13:45 UTC, may- commented
Hi @AmitMY,
`batch_class = Batch` argment is still missing in `validate_on_batch()`call, maybe?

https://github.com/joeynmt/joeynmt/blob/349098f943d5721c59eb8ec37572318b9a8ea0d0/joeynmt/prediction.py#L319-L325

https://github.com/joeynmt/joeynmt/blob/349098f943d5721c59eb8ec37572318b9a8ea0d0/joeynmt/prediction.py#L397-L403

@juliakreutzer FYI

2021-01-16 16:20 UTC, juliakreutzer commented
Thanks @may- for raising this! @AmitMY could you please add this?

2021-01-16 16:36 UTC, may- commented
@AmitMY,  I think `**_kwargs` should also be passed through:

https://github.com/joeynmt/joeynmt/blob/349098f943d5721c59eb8ec37572318b9a8ea0d0/joeynmt/model.py#L144
=>
```python
return self.encoder(self.src_embed(src), src_length, src_mask, **_kwargs)
```
---
https://github.com/joeynmt/joeynmt/blob/349098f943d5721c59eb8ec37572318b9a8ea0d0/joeynmt/model.py#L164-L171
=>
```python
return self.decoder(trg_embed=self.trg_embed(trg_input),
                    [...]
                    trg_mask=trg_mask,
                    **_kwargs)
```
---
https://github.com/joeynmt/joeynmt/blob/349098f943d5721c59eb8ec37572318b9a8ea0d0/joeynmt/encoders.py#L90-L91
=>
```python
def forward(self, embed_src: Tensor, src_length: Tensor, mask: Tensor, **kwargs) \
            -> (Tensor, Tensor):
```

https://github.com/joeynmt/joeynmt/blob/349098f943d5721c59eb8ec37572318b9a8ea0d0/joeynmt/encoders.py#L195-L198
=>
```python
ef forward(self,
                embed_src: Tensor,
                src_length: Tensor,
                mask: Tensor,
                **kwargs) -> (Tensor, Tensor):
```

2021-01-16 19:56 UTC, AmitMY commented
@juliakreutzer please see https://github.com/joeynmt/joeynmt/pull/131 for the fix, sorry for the oversight.

@may- I'm not sure regarding whether they should pass directly to the encoder/decoder, making every encoder have this `**kwargs` seems a bit weird to me. I can understand why you want it though. 
Julia, what do you think about it?