Fixes #148
joeynmt/joeynmt pull request #149
Opened 2021-04-30 11:11 UTC by nicola-decao

2021-05-03 02:47 UTC, juliakreutzer requested changes
Thanks so much, this is indeed not the intended behavior! 
Tests fail, but should be easy to fix.

2021-05-03 07:51 UTC, nicola-decao commented
@juliakreutzer yes my PR is slightly wrong, I'm fixing it now.

2021-05-06 11:59 UTC, MStaniek commented
Can longer sequences have a higher score? It was always intended behaviour for me, because:

1. OpenNMT does it too, no? https://github.com/OpenNMT/OpenNMT-py/blob/master/onmt/translate/beam_search.py#L162
2. If score is (log-)probability, it cannot suddenly get better: if the top beam has probabilities (0.9*0.9*0.9) (where the third token is EOS), then some other beam with probabilities (0.9, 0.8, 0.7) can never get a higher value.

Sorry if its confusing what I wrote.

2021-05-06 12:19 UTC, nicola-decao commented
@MStaniek I don't know how OpenNMT works but when you are using length penalty yes it can change because the log-prob is normlaized.

2021-05-06 13:20 UTC, MStaniek commented
Yes, I see now, thank you!

2021-05-15 19:37 UTC, may- commented
Hi,

I checked your fix on iwslt14 de->en, and I actually saw the improvement:

||||
||||

2021-05-15 19:43 UTC, nicola-decao commented
@may- Nice! :) I will finalize my PR next week btw

2021-05-31 07:48 UTC, hljjjmssyh commented
@may-  
Hi! Could you tell me the configuration about iwslt14 de-en?

2021-06-10 11:09 UTC, may- commented
Hi @hljjjmssyh,
sorry for the delay in my reply.
I uploaded my config here: https://github.com/may-/joeynmt/blob/sentencepiece/configs/transformer_iwslt14_deen_sp.yaml
I averaged 10 checkpoints to get the results I reported above.

I also can provide the trained model, if you need it. Please tell me :)

2022-01-17 23:19 UTC, closed without merging