joeyHF: adapting joeyNMT for Masakhane Benchmark Models on Spaces
joeynmt/joeynmt pull request #164
Opened 2022-01-26 16:38 UTC by chrisemezue

My main work was in the `prediction.py` file. 

I created a `load_params_for_prediction` function which loads the parameters and model needed to perform translation and outputs the model parameters -> `params`.

I then tweaked the `translate,py` file to take in `params` and make translation.

Any idea you have for me to do to not make it conflict with the joeyNMT's `translate,py` file will be very much appreciated.

2022-02-08 19:08 UTC, juliakreutzer commented
Hi @chrisemezue!
Thanks for the code! I think it needs some refactoring before we can merge it, in order to make it easy to read and use and compatible with the rest of JoeyNMT. I'll add detailed comments to the code.
In the meantime, can you please try running
`pytest` and `pylint --rcfile=.pylintrc joeynmt`. The output of pylint should give you some hints how to make the code cleaner, and pytest will flag any unit test issues. Both need to pass without errors before we can merge.
Eventually, your addition should also be tested through a unit test, please add it to `https://github.com/joeynmt/joeynmt/blob/main/test/unit/test_prediction.py`.
Thanks!

2022-02-08 19:46 UTC, juliakreutzer requested changes

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> +    :param cfg_file: path to configuration file. Config file can be the yaml file or the loaded config file
This ambiguity would be helpful to express in the [typing information](https://docs.python.org/3/library/typing.html#) above in line 261.

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> +    '''
Can you please add a comment here why this block is needed?

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
>      Interactive translation function.
Remove this line, seems outdated.

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> +    :param cfg_file: path to configuration file/ configuration file dictionary to load parameters
Typing, see above.

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> +    if isinstance(cfg_file,str):
This block is duplicated - maybe it's worth factoring it out into a separate function in `helpers.py`.

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> -    src_vocab_file = cfg["data"].get("src_vocab", model_dir + "/src_vocab.txt")
Why this reduction of flexibility?

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> +def load_params_for_prediction(cfg_file,ckpt: str):
Please add documentation + typing for what this function returns. Thanks!

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
>          bpe_type, sacrebleu, _, _ = parse_test_args(cfg, mode="translate")
How about returning the dictionary directly by the `parse_test_args` function? This would save us the repeated packing/unpacking.

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> -    logger.info("Loading model from %s", ckpt)
Why is this removed?

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> +def load_params_for_prediction(cfg_file,ckpt: str):
It's important to clarify that the function loads the hyperparameters from the config AND loads the model (parameters).

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> +def translate(params,data,type_:int,output_path=None) -> None:
`type_` as a variable name and as int type is not very expressive: it's not clear from the documentation of the function what it means. 
Please add docstrings to the function.

2022-02-08 19:46 UTC, juliakreutzer commented on joeynmt/prediction.py
> -        while True:
What happened to this interactive mode now? We'd like to keep this as a feature. Perhaps this requires breaking down the translate function into two separate functions.

2022-04-08 12:27 UTC, chrisemezue commented
@juliakreutzer I have made final edits to the code based on your reviews. 
- I took all your reviews into consideration and worked on them.
- I ran the `pytest` and they worked with success. I added the test cases in `https://github.com/joeynmt/joeynmt/blob/main/test/unit/test_prediction.py`. 
- `pylint` ran and I corrected based on its reviews.

2022-05-31 21:38 UTC, juliakreutzer commented
Hi @chrisemezue, thank you so much for the changes! For the remaining requested changes (unresolved comments), did you address them as well or shall we discuss them more?
I have discussed with @may- and we will first merge a solution that doesn't require torchtext, and then revisit your PR. In that way we can make sure that everything works as expected and the dependency issues are resolved.

2022-05-31 22:02 UTC, chrisemezue commented
> Hi @chrisemezue, thank you so much for the changes! For the remaining requested changes (unresolved comments), did you address them as well or shall we discuss them more? I have discussed with @may- and we will first merge a solution that doesn't require torchtext, and then revisit your PR. In that way we can make sure that everything works as expected and the dependency issues are resolved.

I worked on all your comments @juliakreutzer .
Please let me know if there is anywhere I can help.

2022-06-04 18:33 UTC, juliakreutzer commented
Hi @chrisemezue, can you try a merge, now that Joey v2.0 is out?

2022-06-07 17:01 UTC, chrisemezue commented
Okay @juliakreutzer 
I see some conflicts. I will add it to my todo - to resolve the conflicts from my end.

2022-06-28 05:52 UTC, chrisemezue commented
> Hi @chrisemezue, can you try a merge, now that Joey v2.0 is out?

Hi @juliakreutzer . Please I am quite confused what I am to do now in order to merge it.

2022-07-06 15:00 UTC, juliakreutzer commented
Hi @chrisemezue can you try to resolve these? https://github.com/joeynmt/joeynmt/pull/164/conflicts
And test if it runs?

2022-08-27 02:51 UTC, NimaBoscarino commented
Hey there! Are there still conflicts in this PR? When I visit https://github.com/joeynmt/joeynmt/pull/164/conflicts I get a 404. I'm also over at Hugging Face with @chrisemezue, so I'm happy to help out to get this merged!

2023-09-04 01:21 UTC, closed without merging

2023-09-04 01:21 UTC, may- commented
See #213